// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./src/components/base-footer/index.vue')['default']
    BaseHeader: typeof import('./src/components/base-header/index.vue')['default']
    BaseToolbar: typeof import('./src/components/base-toolbar/index.vue')['default']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTag: typeof import('element-plus/es')['ElTag']
  }
}

export { }
